
server:
  port: 8280
    
spring:
  application:
    name: bloop-client

  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    properties:   
      bootstrap:
        servers: localhost:19092,localhost:29092,localhost:39092

      schema:
        registry:
          url: http://localhost:8081

      # Best practice for higher availability in Apache Kafka clients prior to 3.0
      session:
        timeout:
          ms: 45000

    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema:
          registry:
            url: http://localhost:8081

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=test;encrypt=true;trustServerCertificate=true
    username: SA
    password: '{cipher}2a276ee1559d8e93fa5d86311eeb540bc47c7eaef0f3e8a7b98f15a912e8aa08d459985b6210766cdbae9d3875adab3f'

    dbcp2:
      test-while-idle: true
      validation-query: select 1    
    
    # Recommended settings
    hikari:
      data-source-properties:
        cachePrepStmts: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        rewriteBatchedStatements: true
        useLocalSessionState: true
        useServerPrepStmts: true
      # The number of connections that Hikari is going to do to MySQL
      maximum-pool-size: 5

  # Only to initialize data when it is an embedded database. Therefore, this will only work when it's on H2. When not using the bootstrap BeerLoader
  # ith Spring Boot 2.5.1 and above, the new SQL initialization properties support detection of embedded datasources for JDBC and R2DBC. By default, SQL database initialization is only performed when using an embedded in-memory database. To always initialize a SQL database, irrespective of its type, set spring.sql.init.mode to always. Similarly, to disable initialization, set spring.sql.init.mode to never
  # https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes/99c8a8903c9a0a94e2ca29e520d09aee7ec6bac4
  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          # google registration id
          google:
            client-id: '{cipher}f8e52c3bd4a85233d9d46d42a74181c8044f62035b213a9770e220c4f44463583c24fd76f31c8f8b08558e477111f3814a414a5267ef671e50cc7915706ca57025ab7911f03d504dc83382f2bb6eef2b479942977c6dd646a76d23c4acea3023'
            client-secret: '{cipher}ee95ba3b07dced35aa4960179d3d4193ed5ba5923ef781a7d13c5f2a21227e84048b05d541c00c0e5ed0dc5f66614849465044a659d0760a5dc4af5bc89d7b2a'
            scope:
            - email
            - profile

          # facebook registration id
          facebook:
            client-id: '{cipher}c56b42b47254002df1a6dcddcb01d8de80e5981f15f4401dd9b27b9089c6953f'
            client-secret: '{cipher}4b8d97802c93956a76c424b4485ee6d03dffcc278d673579f8b9483669409d044b76ac20827a96bbf044d08685b6fc75af6e0b4486b7b6cc463ad7e49dea3fb9'   
            scope:
            - email
            - public_profile            

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        '[format_sql]': false
    show-sql: true

    ## Bootstrap
    # Among the changes introduced in 2.5.0, it seems now the data.sql script is executed before Hibernate is initialized
    # Since we are relying on the ORM mechanism (i.e. Hibernate) to create the schema from the entity definition, the database table does not exist at the moment the initialization SQL script is executed.    
    defer-datasource-initialization: true

# Setup the log level of a debug for everything in the package structure for "com.microservices"
logging:
  level:
    com:
      microservices: DEBUG
      zaxxer:
        hikari:
          HikariConfig: DEBUG

    # Enable logging for config troubleshooting
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

avro:
  topic:
    name: "avro.stream.word.censorship.topic.v1"

mail-server-config:
  mail-host: "smtp.gmail.com"
  mail-port: 587
  mail-username: "kuvaka.padombo@gmail.com"
  mail-password: '{cipher}054d4131c6d3dd03a2337ffec6f9ef1569217399f12df63196dee1b0906c89a1974e192db2aa0410bb3d6ad428d9431b'
  smtp-auth: "true"
  smtp-secured: "true"
  mail-from: "kuvaka.padombo@gmail.com"
  mail-sender-name: "KP Support Team"

## Word-censorship-service (Override the application properties found in the main branch in the  main code)
flash:
  bloop: 
    word-censorship-service-host: http://localhost:8180

    word-censorship-service-user: BloopCensorshipService
    word-censorship-service-password: '{cipher}96ef0d0b2e18e77c9c279d26cb5266121cfa49906d5639dd2cd2a41f61f5df65'    

encrypt:
  key: ${ENCRYPTION_KEY}

