server:
  port: 8888

# Logging level - Can override logback logging properties in application config
logging:
  level:
    ROOT: INFO
    org:
      spring:
        framework:
          cloud: DEBUG

