DROP DATABASE IF EXISTS bloop;

DROP USER IF EXISTS `bloop`@`localhost`;

CREATE DATABASE IF NOT EXISTS bloop CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS `bloop`@`localhost` IDENTIFIED WITH mysql_native_password BY 'password';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `bloop`.* TO `bloop`@`localhost`;
