/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.microservices.flash.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PlainMessageAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5402324376033182160L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PlainMessageAvroModel\",\"namespace\":\"com.microservices.flash.kafka.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"text\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"dateCreated\",\"type\":[\"null\",\"long\"],\"logicalType\":[\"null\",\"date\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<PlainMessageAvroModel> ENCODER =
      new BinaryMessageEncoder<PlainMessageAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PlainMessageAvroModel> DECODER =
      new BinaryMessageDecoder<PlainMessageAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PlainMessageAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PlainMessageAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PlainMessageAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PlainMessageAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PlainMessageAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PlainMessageAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PlainMessageAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PlainMessageAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.UUID id;
   private java.util.UUID userId;
   private java.lang.String text;
   private java.lang.Long dateCreated;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PlainMessageAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param userId The new value for userId
   * @param text The new value for text
   * @param dateCreated The new value for dateCreated
   */
  public PlainMessageAvroModel(java.util.UUID id, java.util.UUID userId, java.lang.String text, java.lang.Long dateCreated) {
    this.id = id;
    this.userId = userId;
    this.text = text;
    this.dateCreated = dateCreated;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return userId;
    case 2: return text;
    case 3: return dateCreated;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.util.UUID)value$; break;
    case 1: userId = (java.util.UUID)value$; break;
    case 2: text = value$ != null ? value$.toString() : null; break;
    case 3: dateCreated = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.util.UUID getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.util.UUID value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.util.UUID getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.util.UUID value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'text' field.
   * @return The value of the 'text' field.
   */
  public java.lang.String getText() {
    return text;
  }


  /**
   * Sets the value of the 'text' field.
   * @param value the value to set.
   */
  public void setText(java.lang.String value) {
    this.text = value;
  }

  /**
   * Gets the value of the 'dateCreated' field.
   * @return The value of the 'dateCreated' field.
   */
  public java.lang.Long getDateCreated() {
    return dateCreated;
  }


  /**
   * Sets the value of the 'dateCreated' field.
   * @param value the value to set.
   */
  public void setDateCreated(java.lang.Long value) {
    this.dateCreated = value;
  }

  /**
   * Creates a new PlainMessageAvroModel RecordBuilder.
   * @return A new PlainMessageAvroModel RecordBuilder
   */
  public static com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder newBuilder() {
    return new com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder();
  }

  /**
   * Creates a new PlainMessageAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PlainMessageAvroModel RecordBuilder
   */
  public static com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder newBuilder(com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder other) {
    if (other == null) {
      return new com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder();
    } else {
      return new com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new PlainMessageAvroModel RecordBuilder by copying an existing PlainMessageAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new PlainMessageAvroModel RecordBuilder
   */
  public static com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder newBuilder(com.microservices.flash.kafka.avro.model.PlainMessageAvroModel other) {
    if (other == null) {
      return new com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder();
    } else {
      return new com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for PlainMessageAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PlainMessageAvroModel>
    implements org.apache.avro.data.RecordBuilder<PlainMessageAvroModel> {

    private java.util.UUID id;
    private java.util.UUID userId;
    private java.lang.String text;
    private java.lang.Long dateCreated;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.text)) {
        this.text = data().deepCopy(fields()[2].schema(), other.text);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.dateCreated)) {
        this.dateCreated = data().deepCopy(fields()[3].schema(), other.dateCreated);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing PlainMessageAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.microservices.flash.kafka.avro.model.PlainMessageAvroModel other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.text)) {
        this.text = data().deepCopy(fields()[2].schema(), other.text);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dateCreated)) {
        this.dateCreated = data().deepCopy(fields()[3].schema(), other.dateCreated);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.util.UUID getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder setId(java.util.UUID value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.util.UUID getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder setUserId(java.util.UUID value) {
      validate(fields()[1], value);
      this.userId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'text' field.
      * @return The value.
      */
    public java.lang.String getText() {
      return text;
    }


    /**
      * Sets the value of the 'text' field.
      * @param value The value of 'text'.
      * @return This builder.
      */
    public com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder setText(java.lang.String value) {
      validate(fields()[2], value);
      this.text = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'text' field has been set.
      * @return True if the 'text' field has been set, false otherwise.
      */
    public boolean hasText() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'text' field.
      * @return This builder.
      */
    public com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder clearText() {
      text = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'dateCreated' field.
      * @return The value.
      */
    public java.lang.Long getDateCreated() {
      return dateCreated;
    }


    /**
      * Sets the value of the 'dateCreated' field.
      * @param value The value of 'dateCreated'.
      * @return This builder.
      */
    public com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder setDateCreated(java.lang.Long value) {
      validate(fields()[3], value);
      this.dateCreated = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'dateCreated' field has been set.
      * @return True if the 'dateCreated' field has been set, false otherwise.
      */
    public boolean hasDateCreated() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'dateCreated' field.
      * @return This builder.
      */
    public com.microservices.flash.kafka.avro.model.PlainMessageAvroModel.Builder clearDateCreated() {
      dateCreated = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PlainMessageAvroModel build() {
      try {
        PlainMessageAvroModel record = new PlainMessageAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.util.UUID) defaultValue(fields()[0]);
        record.userId = fieldSetFlags()[1] ? this.userId : (java.util.UUID) defaultValue(fields()[1]);
        record.text = fieldSetFlags()[2] ? this.text : (java.lang.String) defaultValue(fields()[2]);
        record.dateCreated = fieldSetFlags()[3] ? this.dateCreated : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PlainMessageAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<PlainMessageAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PlainMessageAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<PlainMessageAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










